import type { Metadata } from "next";
import { DM_Mono, DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import { Footer } from "../components/footer";
import { MobileMenu } from "../components/mobile-menu";
import { Navbar } from "../components/navbar";
import { Sidebar } from "../components/sidebar";
import { Toaster } from "../components/ui/sonner";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const mazaeniDemo = localFont({
  src: [
    {
      path: "../fonts/MazaeniDemo-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/MazaeniDemo-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/MazaeniDemo-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/MazaeniDemo-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/MazaeniDemo-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-mazaeni-demo",
  fallback: ["serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmMono.variable} ${mazaeniDemo.variable} font-sans antialiased`}
      >
        <>
          <Navbar />
          <Sidebar />
          <MobileMenu />
          {children}
          <Footer />
          <Toaster />
        </>
      </body>
    </html>
  );
}
