import { MobileMenu, Navbar, Sidebar } from "@/components/layout";
import { LightboxProvider } from "@/components/lightbox-image";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { DM_Mono, DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const mazaeniDemo = localFont({
  src: [
    {
      path: "../fonts/Mazaeni-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Mazaeni-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Mazaeni-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Mazaeni-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Mazaeni-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-mazaeni",
  fallback: ["serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="format-detection"
        content="telephone=no, date=no, email=no, address=no"
      />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1.0"
      ></meta>
      <body
        className={`${dmSans.variable} ${dmMono.variable} ${mazaeniDemo.variable} font-sans antialiased`}
      >
        <LightboxProvider>
          <Navbar />
          <Sidebar />
          <MobileMenu />
          {children}
          <Toaster />
        </LightboxProvider>
      </body>
    </html>
  );
}
